In [1]:
# Importing Libraries
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt  

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

c:\Users\Vivekk\anaconda3\envs\python_course\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [4]:
df.sample(10)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
743107,Data Analyst,Aviation Production Data Analyst Jobs,"Fort Worth, TX",via Clearance Jobs,Full-time,False,"Texas, United States",2023-03-29 20:02:39,False,False,United States,None,NaN,NaN,CACI,"['windows', 'excel', 'word', 'powerpoint']","{'analyst_tools': ['excel', 'word', 'powerpoin..."
132091,Data Scientist,Data Scientist (Consultant) - (Job Number: LON...,"London, UK",via Monster.co.uk,Full-time,False,United Kingdom,2023-02-13 08:32:34,False,False,United Kingdom,None,NaN,NaN,WorleyParsons,"['python', 'r', 'azure', 'aws', 'snowflake', '...","{'cloud': ['azure', 'aws', 'snowflake', 'datab..."
740258,Cloud Engineer,Senior Infrastructure Engineer,"Brno, Czechia",via Trabajo.org,Full-time,False,Czechia,2023-05-26 21:35:51,False,False,Czechia,None,NaN,NaN,StartupJobs,"['aws', 'linux', 'debian', 'gitlab', 'ansible'...","{'async': ['jira', 'confluence'], 'cloud': ['a..."
507832,Data Analyst,Data Analyst (Financial Services) Senior Consu...,"Charlotte, NC",via ZipRecruiter,Full-time,False,Georgia,2023-02-12 11:55:12,False,False,United States,None,NaN,NaN,Protiviti,"['sql', 'sas', 'sas', 'python', 'express', 'ex...","{'analyst_tools': ['sas', 'excel', 'power bi',..."
53948,Data Analyst,data analyst 1,"Bogotá, Bogota, Colombia",via BeBee Colombia,Full-time,False,Colombia,2023-03-18 06:24:27,True,False,Colombia,None,NaN,NaN,ACIERTA HEADHUNTER,"['c', 'excel']","{'analyst_tools': ['excel'], 'programming': ['..."
736689,Senior Data Analyst,Senior Insights & Analytics Manager,Dubai - United Arab Emirates,via Indeed,Full-time,False,United Arab Emirates,2023-07-20 21:44:48,False,False,United Arab Emirates,None,NaN,NaN,Q-Express Documents Transport,"['sql', 'excel']","{'analyst_tools': ['excel'], 'programming': ['..."
717011,Software Engineer,Senior Software Development Engineer,"Sydney NSW, Australia",via BeBee Australia,Full-time,False,Australia,2023-11-24 02:21:02,True,False,Australia,None,NaN,NaN,Correlate Resources,"['java', 'typescript', 'javascript', 'nosql', ...","{'cloud': ['aws'], 'databases': ['mongodb'], '..."
114932,Software Engineer,Design Engineer EW,"Porto, Portugal",via Empregos Trabajo.org,Full-time,False,Portugal,2023-04-07 08:37:32,True,False,Portugal,None,NaN,NaN,CJR RENEWABLES,['aurora'],{'cloud': ['aurora']}
435293,Data Analyst,Data Analyst - IT/Data Analyst IV - Remote | WFH,Anywhere,via LinkedIn,Full-time,True,"Illinois, United States",2023-11-02 16:02:05,True,False,United States,None,NaN,NaN,Get It Recruit - Information Technology,"['sql', 'azure', 'power bi', 'dax']","{'analyst_tools': ['power bi', 'dax'], 'cloud'..."
479197,Data Engineer,Data Engineer GCP,Peru,via LinkedIn,Full-time,False,Peru,2023-12-07 14:32:47,False,False,Peru,None,NaN,NaN,Indra,"['gcp', 'bigquery']","{'cloud': ['gcp', 'bigquery']}"

In [5]:
dataset = load_dataset('lukebarousse/data_jobs')
df_original = dataset['train'].to_pandas()

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [6]:
df_altered=df_original.copy()

In [7]:
median_salary = df_altered['salary_year_avg'].median()

df_altered['salary_year_avg'] = df_altered['salary_year_avg'].fillna(median_salary)

df_altered.loc[:5,'salary_year_avg']

0    115000.0
1    115000.0
2    115000.0
3    115000.0
4    115000.0
5    115000.0
Name: salary_year_avg, dtype: float64

In [8]:
df_original.loc[:5,'salary_year_avg']

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
Name: salary_year_avg, dtype: float64

In [9]:
df.sample(n=5)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
188576,Data Analyst,Online Data Analyst,Anywhere,via LinkedIn,Part-time,True,United Arab Emirates,2023-09-29 15:24:22,True,False,United Arab Emirates,None,NaN,NaN,TELUS International AI Data Solutions,['go'],{'programming': ['go']}
720965,Data Engineer,"Data Engineer (Python, SQL, Azure)","Brentwood, TN",via Jora,Temp work,False,"New York, United States",2023-10-10 21:06:05,False,False,United States,None,NaN,NaN,VACO,"['python', 'sql', 'azure', 'databricks', 'gdpr']","{'cloud': ['azure', 'databricks'], 'libraries'..."
628618,Data Engineer,Sr. Data Engineer,"New Delhi, Delhi, India",via LinkedIn,Full-time,False,India,2023-11-23 12:15:39,False,False,India,None,NaN,NaN,InvoLead,"['shell', 'python', 'java', 'nosql', 'aws', 'a...","{'analyst_tools': ['power bi', 'tableau'], 'cl..."
763422,Software Engineer,Product Analyst,"Tel Aviv-Yafo, Israel",via LinkedIn,Full-time,False,Israel,2023-12-28 21:22:57,False,False,Israel,None,NaN,NaN,Resident,"['go', 'sql', 'python', 'r']","{'programming': ['go', 'sql', 'python', 'r']}"
15307,Data Analyst,Data Analyst - Finance,Sri Lanka,via LinkedIn,Full-time,False,Sri Lanka,2023-04-05 13:16:25,False,False,Sri Lanka,None,NaN,NaN,International Water Management Institute (IWMI),"['power bi', 'excel', 'sap', 'microsoft teams']","{'analyst_tools': ['power bi', 'excel', 'sap']..."